#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.carbonpx >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.carbonpx=/luci-static/carbonpx
		set luci.main.mediaurlbase=/luci-static/carbonpx
		commit luci
	EOF
fi

exit 0
